---
name: Test

on:
  push:
    branches-ignore:
      - master
      - mainline
    tags-ignore:
      - v*

env:
  IMAGE_NAME: nginx-brotli

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Prepare
      #   run:  |
      #     echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
      #     sudo service docker restart

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1.2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build amd64 image
        uses: docker/build-push-action@v2.9.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ env.IMAGE_NAME }}
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,src=/tmp/.buildx-cache

      - name: List images
        run: |
          docker images

      - name: Build amd64 image
        uses: docker/build-push-action@v2.9.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ env.IMAGE_NAME }}
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,src=/tmp/.buildx-cache

      # - name: Build images for other platforms
      #   uses: docker/build-push-action@v2
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64
      #     push: false
      #     tags: nginx-brotli

      - name: Test
        run: |
          docker run --rm -v $(pwd)/tests.sh:/tests.sh --entrypoint sh nginx-brotli /tests.sh
